---
title: "SNSF Data Management Plan"
format: html
editor: source
---



# Institution {.unnumbered}

ETH Zurich

# Responsibilties {.unnumbered}

Principal Investigator:
(Specify name and email)

Data management plan contact person:
(Specify name and email)

# 1. Data collection and documentation

## 1.1 What data will you collect, observe, generate or re-use? 

## 1.2 How will the data be collected, observed or generated?

## 1.3 What documentation and metadata will you provide with the data?

# 2. Ethics, legal and security issues

## 2.1 How will ethical issues be addressed and handled?

## 2.2 How will data access and security be managed?

## 2.3 How will you handle copyright and Intellectual Property Rights issues?

# 3. Data storage and preservation

## 3.1 How will your data be stored and backed-up during the research?

## 3.2 What is your data preservation plan?

# 4. Data sharing and reuse

## 4.1 How and where will the data be shared?

## 4.2 Are there any necessary limitations to protect sensitive data?

## 4.3 All digital repositories I will choose are conform to the FAIR Data Principles 

## 4.4 I will choose digital repositories maintained by a non-profit organisation